[build]
command = "npm run build"
publish = "./Renting House/rent/build"
base = "./Renting House"
[build.environment]
VARIABLE_NAME = "value"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200